version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5173:5173
    networks:
      - home-library-network
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - home-library-network
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules

  postgres:
    container_name: postgres-database
    build:
      context: .
      dockerfile: ./backend/postgres/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - home-library-network
    volumes:
      - ./backend/docker/db/data:/var/lib/postgresql/data/
networks:
  home-library-network:
    driver: bridge
